### ISSUE TITLE
To include callbacks(to delete mediator instances) while editing the engineering-limit property of the mediator-vm-template.

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MediatorManager#26]
/v1/create-mediator-vm-template offers creating and updating mediator vm templates.
Kindly please clarify whether following is the expectation on updating the engineering-limit of an existing mediator vm, 
1. On updating the engineering limit for an existing mediator vm template shall also manages the paired vms.
2. Instances beyond the configured engineering limit shall be deleted randomly
3. MediatorManager application did not provide the list of randomly deleted information to the end-user. (out of MM's Scope : Further the deleted instance will be in connecting state in the SDN controller. And they shall undergo mediator instance creation probably after spinning up a new mediator vm for those device types)

```mermaid
---
title: Modifying the Engineering limit
config:
  theme: forest
---
sequenceDiagram
    participant ops as Operation's<br/>Engineer
    participant MM as MediatorManager
    participant MMDB as MediatorManager<br/>ConfigFile
    participant MIM as paired-mediator-vms
    note over MMDB : {<br/>template-name : "EricssonTemplate1" <br/> engineering-limit: 100 <br/> paired-mediator-vm-list : ["vmeric1",<br/>"vmeric2"]} 
    ops->>MM: 1 /v1/create-mediator-vm-template 
    Note right of ops: {<br/>template-name : "EricssonTemplate1"<br/> engineering-limit: 80 <br/>..<br/>} 
    MM->>MM : 2
    note over MM : Compares Existing(100) vs desired(80)
    MM->>MMDB : 3. Updates the Engineering limit to 80
    rect rgb(255, 0, 0)
    MM->>ops : 204 no content 
    note left of MM : <br/>(Response shall be returned here <br/>before callback?)
    end
    note over MMDB : {<br/>template-name : "EricssonTemplate1" <br/> engineering-limit: 80 <br/> paired-mediator-vm-list : ["vmeric1",<br/>"vmeric2"]} 
    loop Manages instances in the paired-mediator-vms 
        MM->>MIM: 4. /v1/list-mediator-instances
        MIM->>MM: [] (90 entries)
        MM->>MM : 5
        note over MM : Existing(90) - desired(80) = toDelete(10)
        loop randomly dismantle the calculated toDelete 
        MM ->> MIM : 6. /v1/dismantle-mediator-instance
        rect rgb(255, 0, 0)
        note over MIM : What if error happens here ? <br/> Information shall be logged to EATL <br/> and proceed further? <br/> but in the final response code error shall be reflected.
        end
        end
        MM->>MIM: 7. /v1/list-mediator-instances
        MIM->>MM: [] (80 entries)
        MM->>MM : 8
        note over MM : Existing(80) = desired(80) 
        rect rgb(255, 0, 0)
        note over MM : If Existing != desired ? <br/> we shall proceed further.
        end
    end
```
### Forwarding.yaml
Following callbacks shall be included for the /v1/create-mediator-vm-template, 
1. createMediatorVmTemplateRetrievesListOfMediatorInstances 
```yaml
- forwarding-name: createMediatorVmTemplateRetrievesListOfMediatorInstances 
    uuid: mm-1-0-0-op-fc-is-005
    forwarding-type: ProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: MediatorManager://v1/regard-mediator-instance-manager
          uuid: mm-1-0-0-op-s-im-002
      fc-port-update:
      fc-port-deletion:
        - server-name: MediatorManager://v1/disregard-mediator-instance-manager
          uuid: mm-1-0-0-op-s-im-003
      operation-client-deletion:
    initiating-requests:
      - server-name: MediatorManager://v1/create-mediator-vm-template
        uuid: mm-1-0-0-op-s-im-000
    consequent-requests:
      - client-name: MediatorInstanceManager://v1/list-mediator-instance-managers
        uuid: mm-1-0-0-op-c-is-smim-1-0-0-000
      - client-name: MediatorInstanceManager://v1/list-mediator-instance-managers
        uuid: mm-1-0-0-op-c-is-hmim-1-0-0-000
      - client-name: MediatorInstanceManager://v1/list-mediator-instance-managers
        uuid: mm-1-0-0-op-c-is-emim-1-0-0-000
```
2. createMediatorVmTemplateDeletesExistingMediatorInstance
```yaml
- forwarding-name: createMediatorVmTemplateDeletesExistingMediatorInstance
    uuid: mm-1-0-0-op-fc-is-005
    forwarding-type: ProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: MediatorManager://v1/regard-mediator-instance-manager
          uuid: mm-1-0-0-op-s-im-002
      fc-port-update:
      fc-port-deletion:
        - server-name: MediatorManager://v1/disregard-mediator-instance-manager
          uuid: mm-1-0-0-op-s-im-003
      operation-client-deletion:
    initiating-requests:
      - server-name: MediatorManager://v1/create-mediator-vm-template
        uuid: mm-1-0-0-op-s-im-000
    consequent-requests:
      - client-name: MediatorInstanceManager://v1/dismantle-mediator-instance
        uuid: mm-1-0-0-op-c-im-smim-1-0-0-001
      - client-name: MediatorInstanceManager://v1/dismantle-mediator-instance
        uuid: mm-1-0-0-op-c-im-hmimxx-1-0-0-001
      - client-name: MediatorInstanceManager://v1/dismantle-mediator-instance
        uuid: mm-1-0-0-op-c-im-emim-1-0-0-001
```
### Diagram
1. A sequence diagram shall be included 
### OAS 
1. location of the diagram linked to the description of the /v1/create-mediator-vm-template
2. following callbacks shall be included 
    createMediatorVmTemplateRetrievesListOfMediatorInstances 
    createMediatorVmTemplateDeletesExistingMediatorInstance

### Testing
1. MIM simulator shall be equipped with sample data to simulate the situation that MIM has entries beyond the engineering-limit. But , deletion will not actually delete any entries in the MIM simulator. So , listing the instances after deletion will make the validation fails.
2. Response code 531validation : shall not be verified in the testcase as MIM simulator will not have authentication mechanism
3. Response code 532 validation : shall be verified by manipulating MM's config file to point MIM instance to a false ip-address.(via OAM request, So AA is required)
4. Response code 502 validation : shall be included by implementing MIM's simulator with negative response code.
