### ISSUE TITLE
[Idea] Learning ideal sequence of implementation modules to resolve alarms - machine learning?

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MediatorManager#48]
Learning the the ideal/optimized sequence of implementation modules to be called by the implementation manager could be a matter of machine learning.

For this we need to think about what data we need to consider and keep - we already have the records storing the sequences tried to resolve issues. This can be used for machine learning.
We could either (persistently) store data about those resolving sequences to learn from it in the future, or we can just store data as long as we need for the implementation manager to learn from it and then delete it (immediately) - if we do that, we maybe should somehow at least persistently store what the implementation manager has learned so far.

---  
The error code indicates what module shall be called to fix the observed error.

From [06_CurrentAlarm.yaml](https://github.com/openBackhaul/MediatorManager/blob/v1.0.0_spec/spec/InformationStructure/schemas/06_CurrentAlarm.yaml) - there's the records stored in *past-attempts-to-fix*:
```
        past-attempts-to-fix:
          type: array
          x-key: date-of-attempt
          description: 'List of past attempts to fix the problem'
          items:
            type: object
            required:
              - date-of-attempt
              - response-code
            properties:
              date-of-attempt:
                type: string
                pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})$'
                description: 'Date and time when it was attempted to fix the problem'
              response-code:
                type: integer
                description: 'Code that resulted from the attempt to fix the problem'
```
